version: "3.8"

services:
  backend:
    build: ./back
    container_name: quantum-backend
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - quantum-net

  frontend:
    build: ./front
    container_name: quantum-frontend
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - quantum-net

networks:
  quantum-net:
    driver: bridge